### ISSUE TITLE
submit api not work for bsv20 v1 - mainnet

### ISSUE THREAD

**Issue by zhfnjust** [shruggr/1sat-indexer#15] opened 2023-10-11 14:34 UTC
only work for  nft and bsv20 v2

```
https://v3.ordinals.gorillapool.io/api/tx/5f1789e66a52ff2cf43bcc480e92b91b8cd10b10957e9821f6b779a39f7e900b/submit
```

**Comment by shruggr** [comment] 2023-10-12 14:12
The tokens were minted in the same block they were transferred. They will not be validated until 6 blocks after the mint was mined. This is by design.

**Closed as completed by shruggr** 2023-10-12 14:12 UTC
